<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Application authorization manager must extend the RightsAuthManager class.' => 'Менеджер авторизации приложения должен расширять класс RightsAuthManager.',
  'Application web user must extend the RightsWebUser class.' => 'Пользователь приложения должен расширять класс RightsWebUser.',
  'Congratulations!' => 'Поздравляем!',
  'Install Rights' => 'Установить модуль Rights',
  'Installation failed.' => 'Ошибка установки.',
  'No' => 'Нет',
  'Notice: All your existing data will be lost.' => 'Уведомление: Все существующие данные будут утеряны.',
  'Please confirm if you wish to reinstall.' => 'Пожалуйста, подтвердите, желаете ли Вы выполнить установку наново.',
  'Rights has been installed succesfully.' => 'Модуль Rights успешно установлен.',
  'Rights is already installed!' => 'Модуль Rights уже установлен!',
  'Yes' => 'Да',
  'You can start by generating your authorization items' => 'Вы можете начать с генерирования элементов авторизации',
  'You must be logged in to install Rights.' => 'Вы должны выполнить вход в систему для установки модуля Rights.',
  'here' => 'здесь',
);